#!/usr/bin/env python3
"""
Test script to validate the .lnk file format generated by the web version
Compares the binary structure with expected values
"""

import struct
import sys
import os

def validate_lnk_file(filepath):
    """
    Validates a .lnk file binary structure
    Returns True if valid, False otherwise
    """
    try:
        with open(filepath, 'rb') as f:
            data = f.read()
        
        if len(data) < 76:  # Minimum header size
            print(f"❌ File too small: {len(data)} bytes (minimum 76)")
            return False
        
        # Check header size (should be 0x4C = 76)
        header_size = struct.unpack('<I', data[0:4])[0]
        if header_size != 0x4C:
            print(f"❌ Invalid header size: {header_size} (expected 76)")
            return False
        
        # Check LinkCLSID (Shell Link signature)
        expected_clsid = bytes([
            0x01, 0x14, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00,
            0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46
        ])
        actual_clsid = data[4:20]
        if actual_clsid != expected_clsid:
            print(f"❌ Invalid LinkCLSID signature")
            return False
        
        # Check LinkFlags
        link_flags = struct.unpack('<I', data[20:24])[0]
        print(f"✅ LinkFlags: 0x{link_flags:08X}")
        
        # Check ShowCommand
        show_command = struct.unpack('<I', data[60:64])[0]
        print(f"✅ ShowCommand: {show_command}")
        
        print(f"✅ File structure looks valid!")
        print(f"✅ Total size: {len(data)} bytes")
        
        return True
        
    except Exception as e:
        print(f"❌ Error reading file: {e}")
        return False

def main():
    if len(sys.argv) != 2:
        print("Usage: python test_lnk_validation.py <path-to-lnk-file>")
        sys.exit(1)
    
    lnk_file = sys.argv[1]
    
    if not os.path.exists(lnk_file):
        print(f"❌ File not found: {lnk_file}")
        sys.exit(1)
    
    print(f"🔍 Validating .lnk file: {lnk_file}")
    print("-" * 50)
    
    if validate_lnk_file(lnk_file):
        print("\n🎉 Validation PASSED - .lnk file appears to be valid!")
        sys.exit(0)
    else:
        print("\n💥 Validation FAILED - .lnk file has issues!")
        sys.exit(1)

if __name__ == "__main__":
    main()